// <auto-generated />
namespace Test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DBv2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DBv2));
        
        string IMigrationMetadata.Id
        {
            get { return "202305180255038_DB-v2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
